# Generated by Django 3.0.3 on 2020-02-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='article title')),
                ('overview', models.TextField(blank=True, verbose_name='article preview on frontpage')),
                ('content', models.TextField(verbose_name='article main text')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('comment_count', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('categories', models.ManyToManyField(to='backendBlog.Category')),
            ],
        ),
    ]
