# Generated by Django 3.0.3 on 2020-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendBlog', '0003_remove_article_comment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(verbose_name='article preview on frontpage'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='article title'),
        ),
    ]
