# Generated by Django 3.0.3 on 2020-03-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendBlog', '0004_auto_20200301_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='Some_string', max_length=255, unique=True),
        ),
    ]
