# Generated by Django 3.0.3 on 2020-03-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendBlog', '0006_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='backendBlog.Category'),
        ),
    ]
