# Generated by Django 3.0.3 on 2020-03-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendBlog', '0007_auto_20200301_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='about_me',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='displayed_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
