# Generated by Django 3.0.3 on 2020-03-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendBlog', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
    ]
