# Generated by Django 3.0.3 on 2020-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendBlog', '0010_remove_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='backendBlog.Category'),
        ),
    ]
